### PR TITLE
hardhat, contracts, tests

### PR DESCRIPTION
**Pull request by AndyOooh**
Justs a hardhat skeleton, will continue to work on it.
The structure I went for here is with hardhat as parent to our dApp which will hold the frontend and potentially the backend. Another option to have hardhat be a sibling of dApp or hardhat, frontend and backend all be siblings. I'm not aware of any significant pros or cons of either option, so I went with the one I've done before.

### CODE REVIEW

**Comment by AndyOooh** [comment]
Also note that I have installed hardhat-deploy which slightly changes how to write deploy scripts but overall makes it easier.

**Comment by AndyOooh** [comment]
The hardhat project is more than a skeleton now.

- Restructured the project a bit so root level folders are: dApp and hardhat. dApp should have frontend and backend.
- Added contracts Casino and Token. 
- Casino has a win and a lose function as in Danny's Reward contract. The idea is: frontend determines if a game is won or lost. Communicates that to a backend, which calls either function on the contract. If lose, the bet is deleted- If win, player is awarded the amount * multiplier. The multiplier would be 36 for roulette for example and is stored when a player calls bet from the frontend.
- Casino creates the Token contract on deployment. Token contract mints an amount of tokens (currently 10,000) to Casino. We need to consider tokenomics a bit I think. I have also create an airdrop function which can be called once and takes an array of addresses to mint to and an amount.
- Just like Lottery, there is a purchase function. We can delete this or keep it in tandem with a liquidiyy pool.
- Wrote some tests.

**Comment by mrshappy0** [comment]
This looks great, didn't give it a thorough review but for the sake of time gonna approve. Maybe you could demo it to us today @AndyOooh

**Review by mrshappy0 — APPROVED** [review]

**Comment by mrshappy0** [comment]
We can also go over the merge conflicts here in a call. It's most likely from the roulette game.

**Pull request merged**
